/*
 * Intrinio API
 * Welcome to the Intrinio API! Through our Marketplace, we offer a wide selection of financial data feeds sourced by our own proprietary processes as well as from many data vendors. The primary application of the Intrinio API is for use in third-party applications and integrations or for end-users utilizing the Excel add-in and Google Sheets add-on. The Intrinio API uses HTTPS verbs and a RESTful endpoint structure, which makes it easy to request data from Intrinio. Responses are delivered in JSON format. If you need additional help in using the API, go to our home page (https://intrinio.com) and click on the chat icon in the lower right corner.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.intrinio.api;

import com.intrinio.invoker.ApiException;
import org.threeten.bp.LocalDate;
import com.intrinio.models.MutualFund;
import com.intrinio.models.MutualFundStat;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MutualFundApi
 */
@Ignore
public class MutualFundApiTest {

    private final MutualFundApi api = new MutualFundApi();

    
    /**
     * Get All Mutual Funds
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllMutualFundsTest() throws ApiException {
        String nextPage = null;
        List<MutualFund> response = api.getAllMutualFunds(nextPage);

        // TODO: test validations
    }
    
    /**
     * Get a Mutual Fund by ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMutualFundByIdTest() throws ApiException {
        String identifier = null;
        MutualFund response = api.getMutualFundById(identifier);

        // TODO: test validations
    }
    
    /**
     * Get Stats for a Mutual Fund
     *
     * Returns stats for the  Mutual Fund with the given &#x60;identifier&#x60;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMutualFundStatsTest() throws ApiException {
        String identifier = null;
        LocalDate startDate = null;
        LocalDate endDate = null;
        String nextPage = null;
        List<MutualFundStat> response = api.getMutualFundStats(identifier, startDate, endDate, nextPage);

        // TODO: test validations
    }
    
}
