/*
 * Intrinio API
 * Welcome to the Intrinio API! Through our Marketplace, we offer a wide selection of financial data feeds sourced by our own proprietary processes as well as from many data vendors. The primary application of the Intrinio API is for use in third-party applications and integrations or for end-users utilizing the Excel add-in and Google Sheets add-on. The Intrinio API uses HTTPS verbs and a RESTful endpoint structure, which makes it easy to request data from Intrinio. Responses are delivered in JSON format. If you need additional help in using the API, go to our home page (https://intrinio.com) and click on the chat icon in the lower right corner.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.intrinio.api;

import com.intrinio.invoker.ApiException;
import org.threeten.bp.LocalDate;
import com.intrinio.models.Security;
import com.intrinio.models.StockExchange;
import com.intrinio.models.StockPrice;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for StockExchangeApi
 */
@Ignore
public class StockExchangeApiTest {

    private final StockExchangeApi api = new StockExchangeApi();

    
    /**
     * Filter Stock Exchanges
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void filterStockExchangesTest() throws ApiException {
        String city = null;
        String country = null;
        String countryCode = null;
        String nextPage = null;
        List<StockExchange> response = api.filterStockExchanges(city, country, countryCode, nextPage);

        // TODO: test validations
    }
    
    /**
     * Get All Stock Exchanges
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllStockExchangesTest() throws ApiException {
        String nextPage = null;
        List<StockExchange> response = api.getAllStockExchanges(nextPage);

        // TODO: test validations
    }
    
    /**
     * Get Stock Exchange by ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getStockExchangeByIdTest() throws ApiException {
        String identifier = null;
        StockExchange response = api.getStockExchangeById(identifier);

        // TODO: test validations
    }
    
    /**
     * Get Stock Prices by Exchange
     *
     * Return daily Stock Prices for Securities on the Stock Exchange with &#x60;identifier&#x60; and on the &#x60;price_date&#x60; (or the latest date that prices are available)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getStockExchangePricesTest() throws ApiException {
        String identifier = null;
        LocalDate date = null;
        String nextPage = null;
        List<StockPrice> response = api.getStockExchangePrices(identifier, date, nextPage);

        // TODO: test validations
    }
    
    /**
     * Get Securities by Exchange
     *
     * Return Securities on the Stock Exchange with &#x60;identifier&#x60;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getStockExchangeSecuritiesTest() throws ApiException {
        String identifier = null;
        String nextPage = null;
        List<Security> response = api.getStockExchangeSecurities(identifier, nextPage);

        // TODO: test validations
    }
    
}
